version: "3"
services:
    sqlserver:
        build:
            context: ./ 
            dockerfile: Dockerfile
        environment:
            SA_PASSWORD: "Pass@Word1"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
volumes:
    mssql-server-linux-data:
