version: "3"
services: 
    mssql:
        image: "microsoft/mssql-server-linux:2017-latest"
        ports: 
            - "1433:1433"
        environment: 
            SA_PASSWORD: "Pass@Word1"
            ACCEPT_EULA: "Y"
 